# Generated by Django 5.1.3 on 2024-11-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools_trail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herramienta',
            options={'ordering': ['tipo', 'codigo']},
        ),
        migrations.AlterModelOptions(
            name='operario',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['herramienta']},
        ),
    ]
