# Generated by Django 5.1.3 on 2024-12-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_trail', '0002_alter_herramienta_options_alter_operario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='marca',
            field=models.CharField(default='Generico', max_length=50),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='modelo',
            field=models.CharField(default='Generico', max_length=50),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='tipo',
            field=models.CharField(default='Generico', max_length=50),
        ),
    ]
