# Generated by Django 5.1.3 on 2024-12-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_trail', '0003_alter_herramienta_marca_alter_herramienta_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
